SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS source_call (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider VARCHAR(32) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    request_hash BINARY(32) NOT NULL,
    request_params JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(1000) NULL,
    remote_row_count INT UNSIGNED NOT NULL DEFAULT 0,
    new_entity_count INT UNSIGNED NOT NULL DEFAULT 0,
    new_fact_count INT UNSIGNED NOT NULL DEFAULT 0,
    duration_ms INT UNSIGNED NULL,
    is_cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    data_period_start DATE NULL,
    data_period_end DATE NULL,
    called_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_source_call_request (provider, tool_name, request_hash),
    KEY idx_source_call_called (called_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS source_raw_response (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    call_id BIGINT UNSIGNED NOT NULL,
    response_sha256 BINARY(32) NOT NULL,
    schema_version VARCHAR(64) NULL,
    compression ENUM('none', 'gzip') NOT NULL DEFAULT 'gzip',
    payload MEDIUMBLOB NOT NULL,
    payload_bytes INT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_raw_response (call_id, response_sha256),
    CONSTRAINT fk_raw_call FOREIGN KEY (call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sync_cursor (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider VARCHAR(32) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    scope_hash BINARY(32) NOT NULL,
    scope_params JSON NOT NULL,
    next_page INT UNSIGNED NULL,
    watermark_time DATETIME(3) NULL,
    last_call_id BIGINT UNSIGNED NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sync_scope (provider, tool_name, scope_hash),
    CONSTRAINT fk_cursor_call FOREIGN KEY (last_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_category_scope (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform ENUM('amazon', 'tiktok') NOT NULL,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_category_id VARCHAR(128) NOT NULL,
    category_level TINYINT UNSIGNED NULL,
    category_name VARCHAR(512) NOT NULL,
    category_path VARCHAR(1500) NULL,
    is_bra_leaf BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    source_call_id BIGINT UNSIGNED NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_category_scope (platform, market, provider, external_category_id),
    KEY idx_category_enabled (platform, market, is_bra_leaf, enabled),
    CONSTRAINT fk_category_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_shop (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform ENUM('amazon', 'tiktok') NOT NULL,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_shop_id VARCHAR(128) NOT NULL,
    shop_name VARCHAR(512) NULL,
    shop_type VARCHAR(64) NULL,
    rating DECIMAL(6,3) NULL,
    extra_attributes JSON NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_shop (platform, market, provider, external_shop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_product_family (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform ENUM('amazon', 'tiktok') NOT NULL,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_family_id VARCHAR(128) NOT NULL,
    parent_asin CHAR(10) NULL,
    shop_id BIGINT UNSIGNED NULL,
    category_scope_id BIGINT UNSIGNED NULL,
    brand VARCHAR(255) NULL,
    title VARCHAR(1500) NULL,
    image_url VARCHAR(2000) NULL,
    listed_at DATETIME(3) NULL,
    wire_structure VARCHAR(32) NULL,
    strap_presence VARCHAR(32) NULL,
    closure_type VARCHAR(32) NULL,
    cup_construction VARCHAR(32) NULL,
    cup_coverage VARCHAR(32) NULL,
    back_style VARCHAR(32) NULL,
    band_length VARCHAR(32) NULL,
    pack_size SMALLINT UNSIGNED NULL,
    attribute_confidence DECIMAL(5,4) NULL,
    extra_attributes JSON NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_product_family (platform, market, provider, external_family_id),
    KEY idx_family_attributes (wire_structure, strap_presence, cup_coverage),
    KEY idx_family_shop (shop_id),
    CONSTRAINT fk_family_shop FOREIGN KEY (shop_id) REFERENCES bra_shop(id),
    CONSTRAINT fk_family_category FOREIGN KEY (category_scope_id) REFERENCES bra_category_scope(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_product_variant (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    family_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_product_id VARCHAR(128) NOT NULL,
    sku_external_id VARCHAR(128) NULL,
    color VARCHAR(128) NULL,
    band_size VARCHAR(32) NULL,
    cup_size VARCHAR(32) NULL,
    alpha_size VARCHAR(32) NULL,
    pack_size SMALLINT UNSIGNED NULL,
    currency CHAR(3) NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_variant (provider, external_product_id),
    KEY idx_variant_family (family_id),
    CONSTRAINT fk_variant_family FOREIGN KEY (family_id) REFERENCES bra_product_family(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_offer (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    variant_id BIGINT UNSIGNED NOT NULL,
    shop_id BIGINT UNSIGNED NULL,
    provider VARCHAR(32) NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    currency CHAR(3) NULL,
    price DECIMAL(18,6) NULL,
    list_price DECIMAL(18,6) NULL,
    coupon_value DECIMAL(18,6) NULL,
    commission_rate DECIMAL(10,6) NULL,
    inventory BIGINT NULL,
    fulfillment_type VARCHAR(64) NULL,
    is_available BOOLEAN NULL,
    source_call_id BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    KEY idx_offer_variant_time (variant_id, observed_at),
    CONSTRAINT fk_offer_variant FOREIGN KEY (variant_id) REFERENCES bra_product_variant(id),
    CONSTRAINT fk_offer_shop FOREIGN KEY (shop_id) REFERENCES bra_shop(id),
    CONSTRAINT fk_offer_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_product_daily (
    metric_date DATE NOT NULL,
    provider VARCHAR(32) NOT NULL,
    platform ENUM('amazon', 'tiktok') NOT NULL,
    market CHAR(2) NOT NULL,
    family_id BIGINT UNSIGNED NOT NULL,
    period_days SMALLINT NOT NULL DEFAULT 0,
    currency CHAR(3) NULL,
    price DECIMAL(18,6) NULL,
    rating DECIMAL(6,3) NULL,
    review_count BIGINT NULL,
    units_daily BIGINT NULL,
    units_7d BIGINT NULL,
    units_28d BIGINT NULL,
    units_90d BIGINT NULL,
    units_total BIGINT NULL,
    gmv_daily DECIMAL(20,6) NULL,
    gmv_7d DECIMAL(20,6) NULL,
    gmv_28d DECIMAL(20,6) NULL,
    gmv_90d DECIMAL(20,6) NULL,
    gmv_total DECIMAL(20,6) NULL,
    bsr_rank INT NULL,
    category_rank INT NULL,
    creator_count INT NULL,
    video_count INT NULL,
    live_count INT NULL,
    ad_gmv DECIMAL(20,6) NULL,
    organic_gmv DECIMAL(20,6) NULL,
    ad_spend_est DECIMAL(20,6) NULL,
    is_estimated BOOLEAN NOT NULL DEFAULT TRUE,
    confidence DECIMAL(5,4) NULL,
    source_call_id BIGINT UNSIGNED NULL,
    extra_metrics JSON NULL,
    PRIMARY KEY (metric_date, provider, family_id, period_days),
    KEY idx_product_rank (metric_date, provider, units_28d),
    CONSTRAINT fk_daily_family FOREIGN KEY (family_id) REFERENCES bra_product_family(id),
    CONSTRAINT fk_daily_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_keyword (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    market CHAR(2) NOT NULL,
    keyword VARCHAR(512) NOT NULL,
    normalized_keyword VARCHAR(512) NOT NULL,
    keyword_hash BINARY(32) NOT NULL,
    root_keyword VARCHAR(255) NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_keyword_hash (market, keyword_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_keyword_period (
    provider VARCHAR(32) NOT NULL,
    market CHAR(2) NOT NULL,
    keyword_id BIGINT UNSIGNED NOT NULL,
    period_type ENUM('day', 'week', 'month', 'latest') NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NULL,
    search_volume BIGINT NULL,
    purchase_volume BIGINT NULL,
    purchase_rate DECIMAL(12,8) NULL,
    search_growth DECIMAL(14,8) NULL,
    product_count BIGINT NULL,
    supply_demand_ratio DECIMAL(20,8) NULL,
    click_concentration DECIMAL(12,8) NULL,
    title_density BIGINT NULL,
    spr DECIMAL(20,8) NULL,
    ppc_bid_low DECIMAL(18,6) NULL,
    ppc_bid_high DECIMAL(18,6) NULL,
    avg_price DECIMAL(18,6) NULL,
    source_call_id BIGINT UNSIGNED NULL,
    extra_metrics JSON NULL,
    PRIMARY KEY (provider, market, keyword_id, period_type, period_start),
    KEY idx_keyword_period (keyword_id, period_start),
    CONSTRAINT fk_keyword_fact_keyword FOREIGN KEY (keyword_id) REFERENCES bra_keyword(id),
    CONSTRAINT fk_keyword_fact_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_product_keyword_period (
    provider VARCHAR(32) NOT NULL,
    family_id BIGINT UNSIGNED NOT NULL,
    keyword_id BIGINT UNSIGNED NOT NULL,
    period_start DATE NOT NULL,
    traffic_type VARCHAR(32) NOT NULL DEFAULT 'all',
    organic_rank INT NULL,
    sponsored_rank INT NULL,
    traffic_share DECIMAL(12,8) NULL,
    click_share DECIMAL(12,8) NULL,
    conversion_share DECIMAL(12,8) NULL,
    source_call_id BIGINT UNSIGNED NULL,
    extra_metrics JSON NULL,
    PRIMARY KEY (provider, family_id, keyword_id, period_start, traffic_type),
    CONSTRAINT fk_pk_family FOREIGN KEY (family_id) REFERENCES bra_product_family(id),
    CONSTRAINT fk_pk_keyword FOREIGN KEY (keyword_id) REFERENCES bra_keyword(id),
    CONSTRAINT fk_pk_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_creator (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_creator_id VARCHAR(128) NOT NULL,
    creator_name VARCHAR(512) NULL,
    follower_count BIGINT NULL,
    extra_attributes JSON NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_creator (market, provider, external_creator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_content (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    content_type ENUM('video', 'live') NOT NULL,
    external_content_id VARCHAR(128) NOT NULL,
    creator_id BIGINT UNSIGNED NULL,
    published_at DATETIME(3) NULL,
    description TEXT NULL,
    script_text MEDIUMTEXT NULL,
    is_ad BOOLEAN NULL,
    extra_attributes JSON NULL,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_content (provider, content_type, external_content_id),
    CONSTRAINT fk_content_creator FOREIGN KEY (creator_id) REFERENCES bra_creator(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_content_product_daily (
    metric_date DATE NOT NULL,
    provider VARCHAR(32) NOT NULL,
    content_id BIGINT UNSIGNED NOT NULL,
    family_id BIGINT UNSIGNED NOT NULL,
    creator_id BIGINT UNSIGNED NULL,
    play_count BIGINT NULL,
    like_count BIGINT NULL,
    comment_count BIGINT NULL,
    share_count BIGINT NULL,
    units_sold BIGINT NULL,
    gmv DECIMAL(20,6) NULL,
    commission_est DECIMAL(20,6) NULL,
    source_call_id BIGINT UNSIGNED NULL,
    extra_metrics JSON NULL,
    PRIMARY KEY (metric_date, provider, content_id, family_id),
    CONSTRAINT fk_cpd_content FOREIGN KEY (content_id) REFERENCES bra_content(id),
    CONSTRAINT fk_cpd_family FOREIGN KEY (family_id) REFERENCES bra_product_family(id),
    CONSTRAINT fk_cpd_creator FOREIGN KEY (creator_id) REFERENCES bra_creator(id),
    CONSTRAINT fk_cpd_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bra_review (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform ENUM('amazon', 'tiktok') NOT NULL,
    market CHAR(2) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    external_review_id VARCHAR(128) NULL,
    review_hash BINARY(32) NOT NULL,
    family_id BIGINT UNSIGNED NOT NULL,
    variant_id BIGINT UNSIGNED NULL,
    rating DECIMAL(4,2) NULL,
    review_title VARCHAR(1000) NULL,
    review_text MEDIUMTEXT NULL,
    reviewer_name VARCHAR(255) NULL,
    reviewed_at DATETIME(3) NULL,
    is_verified BOOLEAN NULL,
    is_vine BOOLEAN NULL,
    helpful_count BIGINT NULL,
    language VARCHAR(16) NULL,
    sentiment VARCHAR(24) NULL,
    painpoint_tags JSON NULL,
    source_call_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_review (provider, review_hash),
    KEY idx_review_family_time (family_id, reviewed_at),
    CONSTRAINT fk_review_family FOREIGN KEY (family_id) REFERENCES bra_product_family(id),
    CONSTRAINT fk_review_variant FOREIGN KEY (variant_id) REFERENCES bra_product_variant(id),
    CONSTRAINT fk_review_call FOREIGN KEY (source_call_id) REFERENCES source_call(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

